# Configuración de base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/literalura_db
spring.datasource.username=your_username
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate para crear/drop tables automáticamente (opcional)
spring.jpa.hibernate.ddl-auto=update

# Puerto del servidor
server.port=8080
